version: '3.5'

services:
  db_finance:
    container_name: db_finance
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=brokkko
      - POSTGRES_USER=brokkko
    image: postgres:14.5

  front_server:
    container_name: front_server
    ports:
      - "3000:3000"
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    volumes:
      - ../:/app
    command: .
    depends_on:
      - db_finance