version: '3.5'

services:
  db_finance:
    container_name: db_finance
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=brokkko
      - POSTGRES_USER=brokkko
    image: postgres:14.5