spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: brokkko
    password: brokkko

  jpa:
    hibernate:
      ddl-auto: update

#server:
#  servlet:
#    context-path: /api/v1
